package lt.vu.usecases.mybatis.model;

public class BookstoreWriter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOKSTORE_WRITER.BOOKSTORE_ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    private Integer bookstoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOKSTORE_WRITER.WRITER_ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    private Integer writerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOKSTORE_WRITER.BOOKSTORE_ID
     *
     * @return the value of PUBLIC.BOOKSTORE_WRITER.BOOKSTORE_ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public Integer getBookstoreId() {
        return bookstoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOKSTORE_WRITER.BOOKSTORE_ID
     *
     * @param bookstoreId the value for PUBLIC.BOOKSTORE_WRITER.BOOKSTORE_ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public void setBookstoreId(Integer bookstoreId) {
        this.bookstoreId = bookstoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOKSTORE_WRITER.WRITER_ID
     *
     * @return the value of PUBLIC.BOOKSTORE_WRITER.WRITER_ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public Integer getWriterId() {
        return writerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOKSTORE_WRITER.WRITER_ID
     *
     * @param writerId the value for PUBLIC.BOOKSTORE_WRITER.WRITER_ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public void setWriterId(Integer writerId) {
        this.writerId = writerId;
    }
}