package lt.vu.usecases.mybatis.model;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.WRITER_ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    private Integer writerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.TITLE
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.ID
     *
     * @return the value of PUBLIC.BOOK.ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.ID
     *
     * @param id the value for PUBLIC.BOOK.ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.WRITER_ID
     *
     * @return the value of PUBLIC.BOOK.WRITER_ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public Integer getWriterId() {
        return writerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.WRITER_ID
     *
     * @param writerId the value for PUBLIC.BOOK.WRITER_ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public void setWriterId(Integer writerId) {
        this.writerId = writerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.TITLE
     *
     * @return the value of PUBLIC.BOOK.TITLE
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.TITLE
     *
     * @param title the value for PUBLIC.BOOK.TITLE
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }
}