package lt.vu.usecases.mybatis.model;

public class Bookstore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOKSTORE.ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOKSTORE.TITLE
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOKSTORE.CITY
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOKSTORE.ID
     *
     * @return the value of PUBLIC.BOOKSTORE.ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOKSTORE.ID
     *
     * @param id the value for PUBLIC.BOOKSTORE.ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOKSTORE.TITLE
     *
     * @return the value of PUBLIC.BOOKSTORE.TITLE
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOKSTORE.TITLE
     *
     * @param title the value for PUBLIC.BOOKSTORE.TITLE
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOKSTORE.CITY
     *
     * @return the value of PUBLIC.BOOKSTORE.CITY
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOKSTORE.CITY
     *
     * @param city the value for PUBLIC.BOOKSTORE.CITY
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }
}