package lt.vu.usecases.mybatis.model;

public class Writer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WRITER.ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WRITER.FIRST_NAME
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.WRITER.LAST_NAME
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    private String lastName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WRITER.ID
     *
     * @return the value of PUBLIC.WRITER.ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WRITER.ID
     *
     * @param id the value for PUBLIC.WRITER.ID
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WRITER.FIRST_NAME
     *
     * @return the value of PUBLIC.WRITER.FIRST_NAME
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WRITER.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.WRITER.FIRST_NAME
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.WRITER.LAST_NAME
     *
     * @return the value of PUBLIC.WRITER.LAST_NAME
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.WRITER.LAST_NAME
     *
     * @param lastName the value for PUBLIC.WRITER.LAST_NAME
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}