package lt.vu.usecases.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.Bookstore;

public interface BookstoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKSTORE
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKSTORE
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    int insert(Bookstore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKSTORE
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    Bookstore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKSTORE
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    List<Bookstore> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOKSTORE
     *
     * @mbg.generated Wed May 08 02:15:44 EEST 2019
     */
    int updateByPrimaryKey(Bookstore record);
}