package lt.vu.usecases.mybatis.dao;

import java.util.List;
import lt.vu.usecases.mybatis.model.Writer;

import org.mybatis.cdi.Mapper;

@Mapper
public interface WriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WRITER
     *
     * @mbg.generated Wed May 08 10:40:53 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WRITER
     *
     * @mbg.generated Wed May 08 10:40:53 EEST 2019
     */
    int insert(Writer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WRITER
     *
     * @mbg.generated Wed May 08 10:40:53 EEST 2019
     */
    Writer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WRITER
     *
     * @mbg.generated Wed May 08 10:40:53 EEST 2019
     */
    List<Writer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.WRITER
     *
     * @mbg.generated Wed May 08 10:40:53 EEST 2019
     */
    int updateByPrimaryKey(Writer record);
}