CREATE TABLE IF NOT EXISTS BOOKSTORE
(
	ID INTEGER NOT NULL IDENTITY,
	TITLE            VARCHAR(50),
	CITY            VARCHAR(50),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS WRITER
(
	ID INTEGER NOT NULL IDENTITY,
	FIRST_NAME       VARCHAR(20),
	LAST_NAME        VARCHAR(20),
	PRIMARY KEY (ID),
);

CREATE TABLE IF NOT EXISTS BOOK
(
	ID INTEGER NOT NULL IDENTITY,
	WRITER_ID       INTEGER,
	TITLE             VARCHAR(50),
	PRIMARY KEY (ID),
	FOREIGN KEY (WRITER_ID) REFERENCES WRITER (ID)
);

CREATE TABLE IF NOT EXISTS BOOKSTORE_WRITER
(
	BOOKSTORE_ID      INTEGER,
	WRITER_ID       INTEGER,
	PRIMARY KEY (BOOKSTORE_ID, WRITER_ID),
	FOREIGN KEY (BOOKSTORE_ID) REFERENCES BOOKSTORE (ID),
	FOREIGN KEY (WRITER_ID) REFERENCES WRITER (ID)
);